name: Create WordPress plugin Zip file

on:
  release:
    types: [ released, prereleased ]

jobs:
  build:
    name: Build Plugin Artifact
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v2

      - name: Generate plugin artifact
        run: |
          mkdir -p release/daan-modify-license-check
          rsync -rc --exclude-from="$GITHUB_WORKSPACE/.distignore" "$GITHUB_WORKSPACE/" release/daan-modify-license-check/ --delete --delete-excluded
          cd "${GITHUB_WORKSPACE}/release" || exit
          zip -r "${GITHUB_WORKSPACE}/daan-modify-license-check.zip" .

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{github.workspace}}/daan-modify-license-check.zip
          asset_name: daan-modify-license-check.zip
          asset_content_type: application/zip
